### ISSUE TITLE
Is there a way to pass accelerator='ddp' to PL so pytorch_tabular uses both gpus when training on my box?

### ISSUE THREAD

**Issue by ypopkov** [manujosephv/pytorch_tabular#15]

**Comment by manujosephv** [comment]
No clean way right now. But it's only because I didn't have multiple GPUs to test it. The change is going to be minimal. If you are open to it, you can submit a PR with the change. Or I can create another branch with the distributed training params from PL and you can test if those params work.

Let me know which one works best for you.

**Comment by manujosephv** [comment]
@ypopkov have you had a chance to think about this?

**Comment by ypopkov** [comment]
@manujosephv After evaluating PT, it does not seem worth the effort at this point to switch from a GBM-based model we currently use. It's a great package though - bunch of kudos for putting this together!
