### ISSUE TITLE
continuous feature transform did not fill na, it would cause nan during training process

### ISSUE THREAD

**Issue by Lapis-Hong** [manujosephv/pytorch_tabular#173]
**Describe the bug**

**To Reproduce**

1. Click on '....'
1. Scroll down to '....'
1. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: \[e.g. iOS\]
- Browser \[e.g. chrome, safari\]
- Version \[e.g. 22\]

**Smartphone (please complete the following information):**

- Device: \[e.g. iPhone6\]
- OS: \[e.g. iOS8.1\]
- Browser \[e.g. stock browser, safari\]
- Version \[e.g. 22\]

**Additional context**

**Comment by manujosephv** [comment]
Unfortunately, this is an intentional design choice.. The user is expected to handle NaN's in continuous data. In Categorical data, PyTorch Tabular handles it by treating missing value as an unseen category value. This is a logical way of handling it. But there is not single option like that for continuous variables. 

So, as a principle, missing values are not handled in the library. But I do think we can make it clearer in the documentation and in code as well, by giving warnings and suggestions when there is NaN values. If you are ok to raise a PR for it, it would be great..

**Comment by santurini** [comment]
Sorry @manujosephv, but I actually tried to leave the NaN in the categorical variables but it doesn't handle it, instead it gives me error.

Moreover, I also tried to follow the error suggestion and fill the na with the `pandas.NA` and it still does not work.
My workaround has been this:
```
for c in categorical:
    df[c] = df[c].astype("string") 
    df[c].fillna("na", inplace=True)
```

What does it do internally the library? I thought it called something like a LabelEncoder() that actually can deal with nan.
Sorry for the long post, I'm just curious about it
