### ISSUE TITLE
Customizing OptimizerConfig to handle optimizers and scheduler configuration.

### ISSUE THREAD

**Issue by mdicio** [manujosephv/pytorch_tabular#259]
I think the customization of optimizers and scheddlers could be improved in terms of usability. OptimizerConfig only accepts strings as optimizers and schedulers. Being able to specify both optimizers and schedulers as objects would be great i think. Also only the optimizer can be overridden in the fit method, but not the scheduler.

I think there also might be a potential bug in handling the learning rate. For example if I specify:

tabular_model.fit(
            train=train,
            validation=validation,
            loss=self.loss_fn,
            optimizer=Adam,
            optimizer_params=dict( lr=0.001, weight_decay=0.0001
            )
            
This will raise an error:
TypeError: torch.optim.adam.Adam() got multiple values for keyword argument 'lr'
Also if I try to use the OptimizerConfig class to do the same thing it will give me the same error, forcing me to only specify the weight_decay like this:

 optimizer_config = OptimizerConfig(
                optimizer="Adam",
                optimizer_params={"weight_decay": params["adam_weight_decay"]},...)

Is there a reason for this or is this a potential bug?
I think a possible solution would be to change the functioning of the configure_optimizers method in /models/base_model.py.
If this is not possible maybe being able to pass in actual optimizers and scheduler objects to the OptimizerConfig would also be good.

**Comment by manujosephv** [comment]
The error you are getting is because you are passing in `lr=0.001`. Learning rate is a separate parameter in the `ModelConfig`, which can also be overridden by the same parameter in `fit`. The design was chosen to be like this becaue learning rate was something that should not be buried in the optimizer config, and we also use the learning rate in other places, like finding automatic learning rate, etc.

But I see that this can be a bit more clearer in the error message and documentation.. I'll make those changes.

But in general, there are 2 ways of choosing the optimizer and learning rate schedulers:

1. With the `OptimizerConfig` - This will only work with standard optimizers and LrSchedulers in PyTorch. 
2. For any custom optimizer (which is still a PyTorch optimizer), you can pass the initialised instance through the `fit` method.

There is not option to choose a different LRScheduler, but I guess you can always use the `LambdaLR` in PyTorch to add any custom decay that you want.

And lastly, `OptimizerConfig` was designed to be replicated using a yaml file as well and that is why all the parameters are either strings or numbers  and not actual class instances.

Let me know if this answers your question.. and if you have any more concerns or want to suggest a different way of doing things.. :)

**Comment by BoomHSB** [comment]
Thank you for the clarification, the reason I think this behaviour is a bit strange is because it will throw an error even when I do not pass the lr parameter in the model config, but I understand this is not so important maybe if one knows this behaviour.
Thanks ;)

**Comment by BoomHSB** [comment]
Thank you for the clarification, the reason I think this behaviour is a bit strange is because it will throw an error even when I do not pass the lr parameter in the model config, but I understand this is not so important maybe if one knows this behaviour.
Thanks ;)

**Comment by manujosephv** [comment]
I agree. It's definitely strange. What happens is that if not provided LR is taken as 1e-3 by default. It's designed to only take in LR parameter through model config. So ideally, there should be an assert statement to prevent one from passing LR through the optimiser config.  This is missing now.
