### ISSUE TITLE
initiate Embedding with pre-trained weights

### ISSUE THREAD

**Issue by v71m** [manujosephv/pytorch_tabular#26]
Can a categorical variable embedding layer be intianted with weights?
Something similar to the common practice in text embedding to initiate NN models with pre-computed embedding.
I guess if the pytorch embedding layer is exposed via the pytorch_tabular API, then
https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html?highlight=embedding
>>> # FloatTensor containing pretrained weights
>>> weight = torch.FloatTensor([[1, 2.3, 3], [4, 5.1, 6.3]])
>>> embedding = nn.Embedding.from_pretrained(weight)
would work

**Comment by manujosephv** [comment]
The PyTorch Tabular API doesn't support this out of the box. Will need a bit of hacking to get that done. The issue is that the PyTorch model, under the hood, is only instantiated when the `fit` is called because there are a few information that we derive using the data like the cardinality of the categorical variables etc.

Once the model is fit, you can access the Pytorch model underneath by `tabular_model.model`. But to initialize it before training, Think you will have to create a custom model, where instead of inheriting BaseModel you can inherit the model you want to use(like CategoryEmbeddingModel), and override just the `_build_network` method --> First call `super()._build_network`, and then write the code to initialize the embedding layers

In theory, it should work. i haven't tested this. So let me know if this works out.

**Comment by manujosephv** [comment]
@v71m Were you able to get this to work?

**Comment by v71m** [comment]
No. I didn't get your explanations. I might try to understand it later.
Thanks

**Comment by manujosephv** [comment]
Although 1.5 years late, we have a solution for this. :D 

@v71m v1.0.0 has been released and with it a low-level API where you have access to the model. Checkout tutorials in documentation. That can help you do this.

**Comment by vmorozov** [comment]
Could you please point to the relevant tutorial/documentation?

**Comment by manujosephv** [comment]
In the simple and advanced tutorial, you can see how you can use the low-level API. So in the low level API, you get access to the model before you train or fit the model.

So, you can access the PyTorch model underneath and all the embedding layers, initialise it the way you want and then fit the model.
