### ISSUE TITLE
[Question] predicting out-of-sample for categorical inputs

### ISSUE THREAD

**Issue by fonnesbeck** [manujosephv/pytorch_tabular#35]
I have a question regarding the usage of tabular models when you are trying to use the model to predict out of sample for some categorical input. For example, your dataset may have included some sort of individual or group ID column that was encoded either using one-hot or an embedding, depending on whether `embed_categorical` was set to True or False. After fitting the model, I may get new data that includes observations that include new ID columns. Is there a way for pytorch_tabular to account for this? If I was manually doing one-hot encoding, I could set all of the encodings to zero, but pytorch_tabular does all of this under the hood, so its not clear.

**Comment by manujosephv** [comment]
Good question. PyTorch Tabular is supposed to handle out-of-sample categorical inputs naturally. If it is not, then it's an issue we need to look at.

So apart from NODE, all other models use Categorical Embedding mandatorily. When you use Categorical Embedding, PTabular initializes an additional embedding and reserves it for unseen categories(this will be a random embedding because we don't have information to train the embedding before hand). So any out-of-sample categories are considered as a random vector during inference.

For NODE, there is an option to use LeaveOneOut Encoder(mostly because the original paper uses it and wanted to make the replication possible. But in my experiments, I've found a consistent jump in performance if you use NODE with categorical embedding). And in LeaveOneOut Encoder new categories are handled by using the mean target.

**Comment by fonnesbeck** [comment]
That makes sense. Thanks for the answer!
