### ISSUE TITLE
A bug in tuning module (Grid Search)

### ISSUE THREAD

**Issue by dungpham98** [manujosephv/pytorch_tabular#389]
**Describe the bug**
I try to use Grid Search in my experiment. But instead of using accuracy as a metric, I used f1_score from Sklearn, which yield an error.

**To Reproduce**

from sklearn.metrics import f1_score

Grid search:

result = tuner.tune(
            train=train,
            validation=test,
            search_space=search_space,
            strategy="grid_search",
            #cv=5, # Uncomment this to do a 5 fold cross validation 
            metric=f1_score, # this used to be "accuracy"
            mode="max",
            progress_bar=True,
            verbose=False # Make True if you want to log metrics and params each iteration
        )

**Expected behavior**
Error log:

ValueError: Classification metrics can't handle a mix of multiclass and continuous-multioutput targets

**Quick fix**

So I did found a way to work around this.
I made some changes in file src/pytorch_tabular/tabular_model_tuner.py:  Replace **Line 341** with this line:

`params.update({metric_str: metric(validation[tabular_model_t.config.target], preds['prediction'], average='macro')})`

Hope this helps

**Comment by manujosephv** [comment]
@dungpham98 So, in the `tune` method, the metric can be used in two ways:

1. You can declare the metric in the `ModelConfig` according to the rules [there](https://pytorch-tabular.readthedocs.io/en/latest/apidocs_config/#pytorch_tabular.config.ModelConfig) (The metrics should be one of the functional metrics implemented in ``torchmetrics``). and then use the name if the metric as a string in `tune`
2. You can declare a custom metric, like the one you have done. But that has another set of rules: `We expect callable to be of the form `metric(y_true, y_pred)`. For classification problems, The y_pred is a dataframe with the probabilities for each class (_probability) and a final prediction(prediction). And for Regression, it is a dataframe with a final prediction` Therefore, in your case, you will just need to define a small function which uses the f1_score with the `average=macro` parameter inside the function.

The reason why it's so complicated is because each metric has their own set of parameters. I hope you understand.

**Comment by dungpham98** [comment]
Right, I get your point. I did call a function like this, it works perfectly:

`def F1(y_true, y_pred):`
    `    return f1_score(y_true, y_pred['prediction'], average='macro')`

Thanks for the feedback, I will close this issue :D
