### ISSUE TITLE
Model Resetting Functionality in .fit Function

### ISSUE THREAD

**Issue by enessinanparildi** [manujosephv/pytorch_tabular#55]
I have a piece of code that basically does the following:

```
# Initialize TabularModel object here
tabular_model = model_setup()
rskf = RepeatedStratifiedKFold(n_splits=2, n_repeats=4, random_state=3685134)
for train_index, test_index in rskf.split(X_split, y_split):
     # Get train_df and test_df there
     tabular_model.fit(train=data_df_train, validation=None, reset=True, seed=None)
     result_test = tabular_model.evaluate(data_df_test)
```

I realized that during this repeated k-fold loop the every prediction result except for the very first split is pretty good. Always the results of the first split is noticeably poorer than the others. This suggests to me that reset may not work as intended. By the way, when I take the initialization of TabularModel object inside the loop, then the model performs similarly not so suspiciously well for every k-fold split. However, if I am not mistaken, tabular_model = model_setup() does not initialize any model parameter. Also, adding this block below after evaluate function inside the loop weirdly does not make difference. 

```
for layer in tabular_model.model.children():
   if hasattr(layer, 'reset_parameters'):
       layer.reset_parameters()
```
Still, the model performs suspiciously well for any split after the first one. I am confused by this behavior.

**Comment by manujosephv** [comment]
@enessinanparildi  Because of some engineering decisions, the model is only actually initialized when we call a `fit` with data (this is mainly because we infer a few information from the data and use them to create the network). So, in the code you have, you are training the same model over and over on different folds. 

By the way, why don't you move the `tabular_model = model_setup()` inside the loop? That way, the model is initialized everytime.

And the code you have to reset parameters only resets parameters for s ingle level, which is usually the backbone and the head. To do that recursively, think you need to use `.modules`. [Link](https://discuss.pytorch.org/t/module-children-vs-module-modules/4551/4)

**Comment by manujosephv** [comment]
In the upcoming update to PyTorch Tabular, we have a more granular API with which you can implement this. instead of a single `fit`, we will be able to use a granular api where we can use `prepare_dataloader`, `prepare_model`, and `train` and in that flow, it becomes easier to reset the model.
